modLoader="javafml" 
loaderVersion="[36,)" 
license="All rights reserved"
issueTrackerURL="https://github.com/jmcmahon1999/Mooney/issues"

[[mods]] 
modId="mooney"
version="${file.jarVersion}"
displayName="Mooney"
#updateJSONURL="https://github.com/jmcmahon1999/"
displayURL="https://ducko.net/"
#logoFile="mooney.png"
credits="Forge mod written by Joe McMahon"
authors="TheDukeOfCamorr"
description='''
Mooney mod!

Adds a simple set of uncraftable moon themed coins for use as a currency in your minecraft world.

Mints and banks coming soon!
'''
[[dependencies.mooney]]
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.mooney]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
